Fix media creation in ImageMediaAdapter
sulu/SuluSyliusConsumerBundle pull request #132
Opened 2023-12-07 12:40 UTC by michaelzangerle

The current `ImageMediaAdapter` uses `Sulu\Bundle\MediaBundle\Entity\Media` directly which causes problems when overriding the `Media` entity. This MR fixes it by creating the entity through the repository.

2023-12-07 12:51 UTC, Prokyonn commented on Adapter/ImageMediaAdapter.php
>          $this->syliusImageDownloader = $syliusImageDownloader;
@wachterjohannes should we add a BC bridge here?

2023-12-07 13:31 UTC, wachterjohannes commented on Adapter/ImageMediaAdapter.php
>          $this->syliusImageDownloader = $syliusImageDownloader;
yes please :)

2023-12-07 13:46 UTC, Prokyonn requested changes

2023-12-07 13:46 UTC, Prokyonn commented on Adapter/ImageMediaAdapter.php
> +        MediaRepositoryInterface $mediaRepository
```suggestion
        ?MediaRepositoryInterface $mediaRepository = null
```

2023-12-07 13:46 UTC, Prokyonn commented on Adapter/ImageMediaAdapter.php
> +        $this->mediaRepository = $mediaRepository;
trigger a deprecation message when `$this->mediaRepository === null`, see e.g.
https://github.com/sulu/sulu/blob/2.5/src/Sulu/Bundle/MediaBundle/Controller/CollectionController.php#L125

2023-12-07 13:46 UTC, Prokyonn commented on Adapter/ImageMediaAdapter.php
> +            $media = $this->mediaRepository->createNew();
```suggestion
            $media = $this->mediaRepository ? $this->mediaRepository->createNew() : new Media();
```

2023-12-11 08:43 UTC, Prokyonn approved these changes

2023-12-11 09:07 UTC, wachterjohannes approved these changes

2023-12-11 09:08 UTC, merged